language: c

# Select container based VM (for os == linux).
sudo: false

# Use gcc as the C compiler (clang is also available).
compiler: gcc

# Specify operating systems to test on (linux and/or osx).
os:
  - linux
  - osx

# Environment variables for the build.
env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=LuaJIT-2.0.4
    - LUA=Lua-5.2.4
    - LUA=5.3.2

# Only test changes to the master branch.
branches:
  only:
    - master

# Disable email notifications.
notifications:
  email: false

# Install dependencies (Lua, Luarocks, ...).
install:
  - . .travis/install.sh

# Build (and test?) your project.
script:
  - luarocks make CFLAGS="-Wall -Wextra -O2 -fPIC"
  - (cd tests && lua str.lua)
  - (cd tests && lua mmapcat.lua)
  - (cd tests && lua mmaprev.lua)
  - (cd tests && lua proctest.lua)
  - (cd tests && lua semtest.lua)

